// This file defines all Redux actions used in this app

// Global actions
export const LOCATION_CHANGE = 'LOCATION_CHANGE'
export const Locations = {
	MAIN_PAGE: 'MAIN_PAGE',
	PROFILE_PAGE: 'PROFILE_PAGE',
	LANDING_PAGE: 'LANDING_PAGE'
}
// Landing Action
export const LOG_IN = 'LOG_IN'
export const REGISTER = 'REGISTER'
export const LANDING_TOGGLE = 'LANDING_TOGGLE'
// Main Action
export const LOG_OUT = 'LOG_OUT'
export const POST_ARTICLE = 'POST_ARTICLE'
export const SET_ARTICLE_FILTER = 'SET_ARTICLE_FILTER'
export const ArticleFilters = {
	SHOW_ALL: 'SHOW_ALL',
	BY_TEXT: 'BY_TEXT',
	BY_AUTHOR: 'BY_AUTHOR'
}
export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
// Profile
export const UPDATE_INFO = 'UPDATE_INFO'
export const UPDATE_IMAGE = 'UPDATE_IMAGE'
// Error
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const Errors = {
	LOG_IN_USERNAME: 'LOG_IN_USERNAME',
	LOG_IN_PASSWORD: 'LOG_IN_PASSWORD',
	REGISTER_USERNAME: 'REGISTER_USERNAME',
	REGISTER_PASSWORD: 'REGISTER_PASSWORD',
	REGISTER_EMAIL: 'REGISTER_EMAIL',
	REGISTER_PHONE: 'REGISTER_PHONE',
	REGISTER_BIRTHDAY: 'REGISTER_BIRTHDAY',
	REGISTER_ZIP: 'REGISTER_ZIP',
	UPDATE_USERNAME: 'UPDATE_USERNAME',
	UPDATE_PASSWORD: 'UPDATE_PASSWORD',
	UPDATE_EMAIL: 'UPDATE_EMAIL',
	UPDATE_PHONE: 'UPDATE_PHONE',
	UPDATE_ZIP: 'UPDATE_ZIP'
}